name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Instalamos gradle de forma limpia sin pasarle argumentos incompatibles
    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.0.2'

    # Generamos el ejecutable local y compilamos usando comandos estándar
    - name: Compilar APK
      run: gradle wrapper && ./gradlew :app:assembleDebug

    - name: Subir Archivo APK
      uses: actions/upload-artifact@v4
      with:
        name: detector-ia-apk
        path: app/build/outputs/apk/debug/app-debug.apk
