name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # ESTA ACCION OFICIAL INSTALA Y CORRE GRADLE 8.0.2 CORRECTAMENTE
    - name: Compilar APK con Gradle Action
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.0.2'
        arguments: :app:assembleDebug

    - name: Subir Archivo APK
      uses: actions/upload-artifact@v4
      with:
        name: detector-ia-apk
        path: app/build/outputs/apk/debug/app-debug.apk
