name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configurar Gradle de forma Nativa
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.0.2'

    # AQUÍ CAMBIAMOS EL COMANDO PARA QUE USE EL WRAPPER LOCAL NATIVO
    - name: Compilar APK con Gradle
      run: gradle wrapper && ./gradlew assembleDebug

    - name: Subir Archivo APK
      uses: actions/upload-artifact@v4
      with:
        name: detector-ia-apk
        path: app/build/outputs/apk/debug/app-debug.apk
